characters/urls.py
from django.urls import path
from . import views

app_name = 'characters'

urlpatterns = [
    path('', views.home, name='home'),
    path('characters/<int:id>/', views.character, name='character'),
]

exemplot20/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('characters.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from utils.characters.constants import *

# Create your models here.
class Race (models.Model):
    name = models.CharField(max_length=65)
    size = models.CharField(max_length=2, choices=SIZES_CHOICES, default='MD')

    def __str__(self):
        return self.name
    

class Origin (models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Faith (models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Classe (models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Character (models.Model):
    name = models.CharField(max_length=65)
    level = models.IntegerField()
    att_str = models.IntegerField (default=0)
    att_dex = models.IntegerField (default=0)
    att_con = models.IntegerField (default=0)
    att_int = models.IntegerField (default=0)
    att_sab = models.IntegerField (default=0)
    att_char = models.IntegerField (default=0)
    hit_points = models.IntegerField()
    mana_points = models.IntegerField()
    armor_class = models.IntegerField()
    speed = models.DecimalField(max_digits=6, decimal_places=1)
    background = models.TextField()
    #Fixed choices
    size = models.CharField(max_length=2, choices=SIZES_CHOICES)
    role = models.CharField(max_length=3, choices=ROLES_CHOICES)
    picture = models.ImageField(upload_to='characters/pictures/%Y/%m/%d' )
    #ForeignKeys
    player = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    race = models.ForeignKey(
        Race, on_delete=models.CASCADE
    )
    origin = models.ForeignKey(
        Origin, on_delete=models.CASCADE
    )
    faith = models.ForeignKey(
        Faith, on_delete=models.SET_NULL, null=True
    )
    #MUDAR FUTURAMENTE PARA MANY TO MANY
    classes = models.ForeignKey(
        Classe, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

characters/views.py
from django.shortcuts import render
from utils.characters.factory import make_character

# Create your views here.
def home (request):
    return render (request, 'characters/pages/home.html', context={
        'characters': [make_character() for _ in range(10)],
    })

# Character detail
def character (request, id):
    return render (request, 'characters/pages/character-view.html', context={
        'character': make_character(),
        'is_it_detail': True 
    })

characters/templates/characters/pages/character-view.html
{% extends "global/base.html" %}<!-- Arquivo Base do site -->

{% block title %}ALTERAR |{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include "characters/partials/character_item.html" %} <!-- Inclusão do item da lista -->


    </div>
{% endblock content %}

characters/templates/characters/pages/home.html
{% extends "global/base.html" %}<!-- Arquivo Base do site -->

{% block title %}Home |{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
         <!-- Inclusão do item da lista -->
        {% for character in characters %}
            {% include "characters/partials/character_item.html" %}
        {% endfor %}
    </div>
{% endblock content %}

characters/templates/characters/partials/character_item.html
<!-- Arquivo dos itens do grid na página inicial -->

<div class="character character-list-item">
    <div class="character-cover">
        <a href="{% url "characters:character" character.id %}"><img src="{{ character.cover.url }}" alt="Temporário"></a>
    </div>

    <div class="character-title-container">
        <a href="{% url "characters:character" character.id %}">
            <h2 class="character-title">
                {{ character.name }} - {{ character.race }} - {{ character.class }}
            </h2>
        </a>
    </div>

    <div class="character-author">
        <span class="character-author-item">
            <i class="fas fa-user"></i>
            {{ character.player.first_name }} {{ character.player.last_name }}
        </span>
        <span class="character-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ character.created_at|date:'d/m/Y' }} às {{ character.created_at|date:'H:i' }}
        </span>
        <!-- É PRECISO AJUSTAR ESSE LINK PARA SER DINAMICO -->
        <span class="character-author-item">
            <a href="/characters/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>{{ character.function }}</span>
            </a>
        </span>
    </div>

    <div class="character-content">
        <p>{{ character.introduction }}</p>
    </div>

    <!-- Este item deve ter os detalhes trocados que serão pensados noutro momento, por enquanto o importante é replicar -->
    <div class="character-meta-container">
        <div class="character-meta character-preparation">
            <h3 class="character-meta-title"><i class="fas fa-magic"></i> Magias</h3>
            <div class="character-meta-text">
                {{ character.spells }} {{ character.spells_unit }}
            </div>
        </div>
        <div class="character-meta character-servings">
            <h3 class="character-meta-title"><i class="fas fa-dumbbell"></i> Perícias</h3>
            <div class="character-meta-text">
                {{ character.skills }} {{ character.skills_unit }}
            </div>
        </div>
    </div>

    {% if is_it_detail is not True %}
        <footer class="character-footer">
            <a class="character-read-more button button-dark button-full-width" href="{% url "characters:character" character.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_it_detail is True %}
        <div class="character-background">
            {{ character.background|linebreaksbr }}
        </div>
    {% endif %}
</div>

characters/templates/characters/partials/footer.html
<!-- Rodapé padrão do site -->

<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Otávio Miranda</a>
    </div>
    
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

characters/templates/characters/partials/head.html
<!-- Arquivo do HEAD do html -->
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Fontes awesome e do google aplis -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'characters/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">

characters/templates/characters/partials/header.html
<!-- Cabeçalho da Página -->

<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url "characters:home" %}">
                <i class="fas fa-dice-d20 main-logo-icon"></i>
                <span class="main-logo-text">Taverna</span>
            </a>
        </h1>
    </div>
</header>

characters/templates/characters/partials/search.html
<!-- Formulário de Pesquisa -->

<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>